version: "3"

services:
  # web:
  #   container_name: web
  #   build:
  #     context: .
  #     dockerfile: ./apps/web/Dockerfile
  #   image: web:latest
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - app_network
  #   environment:
  #     - NEXT_PUBLIC_GATEWAY=http://localhost:8080
  #     - AUTH0_BASE_URL=http://localhost:3000
  #     - AUTH0_SECRET=tJSN-FZrXT6RNOTmC8RYfOnnb7udWlOiHrDfogqJZZjqS4pz9ypEJiJLkfr54VMr
  #     - AUTH0_ISSUER_BASE_URL=https://dev-5citnzhh5o3wou8l.eu.auth0.com
  #     - AUTH0_CLIENT_ID=cgVtxmQp5rL4G0CnwSs6uBJfV1mWGbX3
  #     - AUTH0_CLIENT_SECRET=tJSN-FZrXT6RNOTmC8RYfOnnb7udWlOiHrDfogqJZZjqS4pz9ypEJiJLkfr54VMr
  #     - NEXTAUTH_SECRET=YAFRg5wxr565mAeCEifXT9RfjmSXOOt4IV3Db1+e/3o=
  #     - DATABASE_URL=mongodb+srv://webdeveloper:24IPXOmgrD4mIToV@clusterblinddate.qm39mdu.mongodb.net/test

  user-service:
    container_name: user-service
    build:
      context: .
      dockerfile: ./apps/user-service/Dockerfile
    image: user-service:latest
    restart: always
    ports:
      - 3002:3002
    networks:
      - app_network
    env_file:
      - .env
    depends_on:
      - krakend
  post-service:
    container_name: post-service
    build:
      context: .
      dockerfile: ./apps/post-service/Dockerfile
    image: post-service:latest
    restart: always
    ports:
      - 3003:3003
    networks:
      - app_network
    env_file:
      - .env
    depends_on:
      - krakend
  comment-service:
    container_name: comment-service
    build:
      context: .
      dockerfile: ./apps/comment-service/Dockerfile
    image: comment-service:latest
    restart: always
    ports:
      - 3004:3004
    networks:
      - app_network
    env_file:
      - .env
    depends_on:
      - krakend

  krakend:
    container_name: krakend
    build:
      context: ./krakend
      dockerfile: ./Dockerfile
    image: krakend:latest
    ports:
      - "8080:8080"
    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname.
# test
networks:
  app_network:
    external: true
