# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: api-gateway-ingress
#   annotations:
#     kubernetes.io/ingress.class: "nginx"
#     nginx.ingress.kubernetes.io/rewrite-target: /$1
#     cert-manager.io/cluster-issuer: "letsencrypt"
# spec:
#   tls:
#     - hosts:
#         - api.blinddateg3.xyz
#       secretName: blinddateg3-api-tls
#   rules:
#     - host: api.blinddateg3.xyz
#       http:
#         paths:
#         - pathType: Prefix
#           path: /
#           backend:
#             service:
#               name: krakend-service
#               port:
#                 number: 8000

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: krakend-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  tls:
    - hosts:
        - krakend.blinddateg3.xyz
      secretName: blinddateg3-krakend-tls
  rules:
  - host: krakend.blinddateg3.xyz
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: krakend-service
            port:
              number: 8000

