apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - post-service-deployment.yaml
  - comment-service-deployment.yaml
  - user-service-deployment.yaml
  - upload-service-deployment.yaml
  - api-gateway-ingress.yaml
  - cors-plugin.yaml
  - cluster-issuer.yaml
  - secrets.yaml

images:
  - name: spContaineRegistry.azurecr.io/post-service
    newName: spContaineRegistry.azurecr.io/post-service
    newTag: CICD_PLACEHOLDER
  - name: spContaineRegistry.azurecr.io/comment-service
    newName: spContaineRegistry.azurecr.io/comment-service
    newTag: CICD_PLACEHOLDER
  - name: spContaineRegistry.azurecr.io/user-service
    newName: spContaineRegistry.azurecr.io/user-service
    newTag: CICD_PLACEHOLDER
  - name: spContaineRegistry.azurecr.io/upload-service
    newName: spContaineRegistry.azurecr.io/upload-service
    newTag: CICD_PLACEHOLDER
