apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service-deployment
  labels:
    app: post-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-service
  template:
    metadata:
      labels:
        io.kompose.network/app-network: "true"
        app: post-service
    spec:
      containers:
        - image: stassig/project-post-service
          name: post-service
          ports:
            - containerPort: 3003
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 250m
              memory: 256Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: post-service
  labels:
    app: post-service-k8s
spec:
  ports:
    - name: "3003"
      port: 3003
      targetPort: 3003
  selector:
    app: post-service
