apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
  DATABASE_URL: bW9uZ29kYitzcnY6Ly93ZWJkZXZlbG9wZXI6MjRJUFhPbWdyRDRtSVRvVkBjbHVzdGVyYmxpbmRkYXRlLnFtMzltZHUubW9uZ29kYi5uZXQvdGVzdA==
  S3_BUCKET_NAME: YmxpbmQtZGF0ZS11cGxvYWRz
  S3_BUCKET_REGION: ZXUtbm9ydGgtMQ==
  S3_ACCESS_KEY: QUtJQVNNNVlXRDdHNUlUU0U2VUo=
  S3_SECRET_ACCESS_KEY: NDlsNVlUazZlaEtQZmRPNlh6NGtDYU1CK0I0ai81R2pveVpDdEtnbQ==
