{
 "title": "Crash/Restart Metrics & Logging",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "User Service Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{container=\"user-service\"}"
    }
   ]
  },
  {
   "title": "User Service Restarts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"user-service\"} |= \"api running on 3002\" [5m])) by (container)"
    }
   ]
  },
  {
   "title": "Post Service Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "{container=\"post-service\"}"
    }
   ]
  },
  {
   "title": "Post Service Restarts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"post-service\"} |= \"api running on 3003\" [5m])) by (container)"
    }
   ]
  },
  {
   "title": "Comment Service Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{container=\"comment-service\"}"
    }
   ]
  },
  {
   "title": "Comment Service Restarts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"comment-service\"} |= \"api running on 3004\" [5m])) by (container)"
    }
   ]
  },
  {
   "title": "API Gateway Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "{container=\"krakend\"}"
    }
   ]
  }
 ]
}